//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebAppPortalAD.ADServicios {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISerWebApp", Namespace="http://tempuri.org/")]
    public partial class SerWebApp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CrearUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BloquerCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesbloquearCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaOUOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaUsuariosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SerWebApp() {
            this.Url = global::WebAppPortalAD.Properties.Settings.Default.WebAppPortalAD_ADServicios_SerWebApp;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CrearUsuarioCompletedEventHandler CrearUsuarioCompleted;
        
        /// <remarks/>
        public event ValidarCuentaCompletedEventHandler ValidarCuentaCompleted;
        
        /// <remarks/>
        public event BloquerCuentaCompletedEventHandler BloquerCuentaCompleted;
        
        /// <remarks/>
        public event DesbloquearCuentaCompletedEventHandler DesbloquearCuentaCompleted;
        
        /// <remarks/>
        public event ListaOUCompletedEventHandler ListaOUCompleted;
        
        /// <remarks/>
        public event ListaUsuariosCompletedEventHandler ListaUsuariosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISerWebApp/CrearUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CrearUsuario(
                    string UsuarioIngreso, 
                    string ClaveIngreso, 
                    string Nombre1, 
                    string Nombre2, 
                    string Apellido1, 
                    string Apellido2, 
                    string Identificacion, 
                    string NombreUsuario, 
                    string Email, 
                    string Telefono, 
                    string Compania, 
                    string Departamento, 
                    string Titulo, 
                    string Contrasenia, 
                    string Portal, 
                    string Estado, 
                    string EstadoProceso) {
            object[] results = this.Invoke("CrearUsuario", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Nombre1,
                        Nombre2,
                        Apellido1,
                        Apellido2,
                        Identificacion,
                        NombreUsuario,
                        Email,
                        Telefono,
                        Compania,
                        Departamento,
                        Titulo,
                        Contrasenia,
                        Portal,
                        Estado,
                        EstadoProceso});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(
                    string UsuarioIngreso, 
                    string ClaveIngreso, 
                    string Nombre1, 
                    string Nombre2, 
                    string Apellido1, 
                    string Apellido2, 
                    string Identificacion, 
                    string NombreUsuario, 
                    string Email, 
                    string Telefono, 
                    string Compania, 
                    string Departamento, 
                    string Titulo, 
                    string Contrasenia, 
                    string Portal, 
                    string Estado, 
                    string EstadoProceso) {
            this.CrearUsuarioAsync(UsuarioIngreso, ClaveIngreso, Nombre1, Nombre2, Apellido1, Apellido2, Identificacion, NombreUsuario, Email, Telefono, Compania, Departamento, Titulo, Contrasenia, Portal, Estado, EstadoProceso, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioAsync(
                    string UsuarioIngreso, 
                    string ClaveIngreso, 
                    string Nombre1, 
                    string Nombre2, 
                    string Apellido1, 
                    string Apellido2, 
                    string Identificacion, 
                    string NombreUsuario, 
                    string Email, 
                    string Telefono, 
                    string Compania, 
                    string Departamento, 
                    string Titulo, 
                    string Contrasenia, 
                    string Portal, 
                    string Estado, 
                    string EstadoProceso, 
                    object userState) {
            if ((this.CrearUsuarioOperationCompleted == null)) {
                this.CrearUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioOperationCompleted);
            }
            this.InvokeAsync("CrearUsuario", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Nombre1,
                        Nombre2,
                        Apellido1,
                        Apellido2,
                        Identificacion,
                        NombreUsuario,
                        Email,
                        Telefono,
                        Compania,
                        Departamento,
                        Titulo,
                        Contrasenia,
                        Portal,
                        Estado,
                        EstadoProceso}, this.CrearUsuarioOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioOperationCompleted(object arg) {
            if ((this.CrearUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioCompleted(this, new CrearUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISerWebApp/ValidarCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidarCuenta(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            object[] results = this.Invoke("ValidarCuenta", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarCuentaAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            this.ValidarCuentaAsync(UsuarioIngreso, ClaveIngreso, Usuario, Clave, null);
        }
        
        /// <remarks/>
        public void ValidarCuentaAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave, object userState) {
            if ((this.ValidarCuentaOperationCompleted == null)) {
                this.ValidarCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarCuentaOperationCompleted);
            }
            this.InvokeAsync("ValidarCuenta", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave}, this.ValidarCuentaOperationCompleted, userState);
        }
        
        private void OnValidarCuentaOperationCompleted(object arg) {
            if ((this.ValidarCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarCuentaCompleted(this, new ValidarCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISerWebApp/BloquerCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BloquerCuenta(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            object[] results = this.Invoke("BloquerCuenta", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BloquerCuentaAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            this.BloquerCuentaAsync(UsuarioIngreso, ClaveIngreso, Usuario, Clave, null);
        }
        
        /// <remarks/>
        public void BloquerCuentaAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave, object userState) {
            if ((this.BloquerCuentaOperationCompleted == null)) {
                this.BloquerCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBloquerCuentaOperationCompleted);
            }
            this.InvokeAsync("BloquerCuenta", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave}, this.BloquerCuentaOperationCompleted, userState);
        }
        
        private void OnBloquerCuentaOperationCompleted(object arg) {
            if ((this.BloquerCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BloquerCuentaCompleted(this, new BloquerCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISerWebApp/DesbloquearCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DesbloquearCuenta(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            object[] results = this.Invoke("DesbloquearCuenta", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DesbloquearCuentaAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            this.DesbloquearCuentaAsync(UsuarioIngreso, ClaveIngreso, Usuario, Clave, null);
        }
        
        /// <remarks/>
        public void DesbloquearCuentaAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave, object userState) {
            if ((this.DesbloquearCuentaOperationCompleted == null)) {
                this.DesbloquearCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesbloquearCuentaOperationCompleted);
            }
            this.InvokeAsync("DesbloquearCuenta", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave}, this.DesbloquearCuentaOperationCompleted, userState);
        }
        
        private void OnDesbloquearCuentaOperationCompleted(object arg) {
            if ((this.DesbloquearCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesbloquearCuentaCompleted(this, new DesbloquearCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISerWebApp/ListaOU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListaOU(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            object[] results = this.Invoke("ListaOU", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListaOUAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave) {
            this.ListaOUAsync(UsuarioIngreso, ClaveIngreso, Usuario, Clave, null);
        }
        
        /// <remarks/>
        public void ListaOUAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave, object userState) {
            if ((this.ListaOUOperationCompleted == null)) {
                this.ListaOUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaOUOperationCompleted);
            }
            this.InvokeAsync("ListaOU", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave}, this.ListaOUOperationCompleted, userState);
        }
        
        private void OnListaOUOperationCompleted(object arg) {
            if ((this.ListaOUCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaOUCompleted(this, new ListaOUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISerWebApp/ListaUsuarios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListaUsuarios(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave, string UO) {
            object[] results = this.Invoke("ListaUsuarios", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave,
                        UO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListaUsuariosAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave, string UO) {
            this.ListaUsuariosAsync(UsuarioIngreso, ClaveIngreso, Usuario, Clave, UO, null);
        }
        
        /// <remarks/>
        public void ListaUsuariosAsync(string UsuarioIngreso, string ClaveIngreso, string Usuario, string Clave, string UO, object userState) {
            if ((this.ListaUsuariosOperationCompleted == null)) {
                this.ListaUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaUsuariosOperationCompleted);
            }
            this.InvokeAsync("ListaUsuarios", new object[] {
                        UsuarioIngreso,
                        ClaveIngreso,
                        Usuario,
                        Clave,
                        UO}, this.ListaUsuariosOperationCompleted, userState);
        }
        
        private void OnListaUsuariosOperationCompleted(object arg) {
            if ((this.ListaUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaUsuariosCompleted(this, new ListaUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CrearUsuarioCompletedEventHandler(object sender, CrearUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ValidarCuentaCompletedEventHandler(object sender, ValidarCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void BloquerCuentaCompletedEventHandler(object sender, BloquerCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BloquerCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BloquerCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DesbloquearCuentaCompletedEventHandler(object sender, DesbloquearCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesbloquearCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesbloquearCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListaOUCompletedEventHandler(object sender, ListaOUCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaOUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaOUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListaUsuariosCompletedEventHandler(object sender, ListaUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591